INSERT INTO public.ai_prompt_presets (id, user_id, name, action, system_prompt, is_default, created_at, is_system) VALUES ('41155144-978d-4503-8264-7be22281a95b', NULL, 'Built-in Chat', 'chat', 'You are a helpful assistant for a personal reading library.', false, now(), true);
INSERT INTO public.ai_prompt_presets (id, user_id, name, action, system_prompt, is_default, created_at, is_system) VALUES ('3417a16b-c2fb-4ad2-b25b-f22fdabb5640', NULL, 'Built-in Custom', 'custom', 'You are a helpful assistant for a personal reading library.', false, now(), true);
INSERT INTO public.ai_prompt_presets (id, user_id, name, action, system_prompt, is_default, created_at, is_system) VALUES ('4ca0b1b3-c537-4b99-bd81-e5846143371c', NULL, 'Built-in Summary', 'summary', 'You write summaries for a personal reading library. Write one paragraph of 2 to 4 sentences that captures the central idea, the most important supporting points, and the main takeaway. Apply the same style to every summary: present tense, active voice, plain declarative sentences. Open with the subject matter itself, never with framing such as "This article", "The author", or "In this piece". Use only periods and commas for punctuation. Do not use dashes, semicolons, colons, parentheses, question marks, or exclamation marks. Do not use bullet points or headings. Do not address the reader. Use only the supplied content. Do not invent facts, numbers, or names. Do not editorialize or add praise.', false, now(), true);
INSERT INTO public.ai_prompt_presets (id, user_id, name, action, system_prompt, is_default, created_at, is_system) VALUES ('50faa531-c365-47de-8731-1161763525db', NULL, 'Built-in Tags', 'tags', 'You suggest retrieval-friendly tags for a personal reading library. Suggest 3 to 8 short lowercase tags. Prefer reusable nouns or noun phrases. Avoid duplicates, stopwords, and generic tags like article, reading, link, website, or note.', false, now(), true);
INSERT INTO public.ai_prompt_presets (id, user_id, name, action, system_prompt, is_default, created_at, is_system) VALUES ('1d372731-f019-45df-9d8f-20996712d22c', NULL, 'Built-in Entities', 'entities', 'You extract named entities so the reader can rediscover related content later. Extract only entities genuinely discussed in the content: specific people, organizations, places, events, or named works (books, papers, films, products, projects). Skip the document''s own title, its author or byline, the website, platform, or newsletter it was published on, and generic technologies, tools, or categories that are not proper names. Prefer fewer, higher-signal entities. When the same person, organization, or work is referred to in multiple forms, emit the single most complete form that appears in the content and do not also emit shorter fragments of it. For organizations and products, use the most specific proper name actually used; do not collapse a product into its parent brand or vice versa. For each entity, include its name, entity_type, description, mention_count, and aliases. entity_type must be one of person, organization, location, event, or work. description should be null or a short factual phrase grounded in the content. mention_count must be an integer of at least 1. aliases is a list of the entity''s well-known alternate names, including synonyms and acronyms (for example Facebook for Meta, or AWS for Amazon Web Services), or an empty list if none.', false, now(), true);

INSERT INTO public.feed_provider_instances (id, provider_type, base_url, priority, enabled, last_success_at, last_failure_at, consecutive_failures, created_at, updated_at) VALUES ('017a3ca4-39a6-4d32-b9bb-1163f683b8bb', 'rsshub', 'https://rsshub.pseudoyu.com', 10, true, NULL, NULL, 0, now(), now());
INSERT INTO public.feed_provider_instances (id, provider_type, base_url, priority, enabled, last_success_at, last_failure_at, consecutive_failures, created_at, updated_at) VALUES ('c580d414-3047-4ed8-bee2-be888ab3f1e0', 'rsshub', 'https://rsshub.rssforever.com', 20, true, NULL, NULL, 0, now(), now());
INSERT INTO public.feed_provider_instances (id, provider_type, base_url, priority, enabled, last_success_at, last_failure_at, consecutive_failures, created_at, updated_at) VALUES ('5dce5467-3938-43e2-b785-8780ddd1f76b', 'rsshub', 'https://hub.slarker.me', 30, true, NULL, NULL, 0, now(), now());
INSERT INTO public.feed_provider_instances (id, provider_type, base_url, priority, enabled, last_success_at, last_failure_at, consecutive_failures, created_at, updated_at) VALUES ('e19a024c-caff-4301-83e4-8dc49a8381b7', 'rsshub', 'https://rsshub.ktachibana.party', 40, true, NULL, NULL, 0, now(), now());
INSERT INTO public.feed_provider_instances (id, provider_type, base_url, priority, enabled, last_success_at, last_failure_at, consecutive_failures, created_at, updated_at) VALUES ('9ae4443d-54a9-4c46-bb46-21c63d334b57', 'rsshub', 'https://rsshub.rss.tips', 50, true, NULL, NULL, 0, now(), now());
INSERT INTO public.feed_provider_instances (id, provider_type, base_url, priority, enabled, last_success_at, last_failure_at, consecutive_failures, created_at, updated_at) VALUES ('cd1e208a-51da-4bac-a473-1ebe1ddfed39', 'rsshub', 'https://rss.owo.nz', 60, true, NULL, NULL, 0, now(), now());
INSERT INTO public.feed_provider_instances (id, provider_type, base_url, priority, enabled, last_success_at, last_failure_at, consecutive_failures, created_at, updated_at) VALUES ('ce0c9f2c-cf33-41df-8a65-2f176f50377f', 'rsshub', 'https://rsshub.henry.wang', 70, true, NULL, NULL, 0, now(), now());
INSERT INTO public.feed_provider_instances (id, provider_type, base_url, priority, enabled, last_success_at, last_failure_at, consecutive_failures, created_at, updated_at) VALUES ('680198f3-5432-45dc-97b4-35f4357e3009', 'rsshub', 'https://rsshub.isrss.com', 80, true, NULL, NULL, 0, now(), now());
INSERT INTO public.feed_provider_instances (id, provider_type, base_url, priority, enabled, last_success_at, last_failure_at, consecutive_failures, created_at, updated_at) VALUES ('fd374d85-2cb4-4d63-9563-0b337a67a790', 'nitter', 'https://nitter.net', 10, true, NULL, NULL, 0, now(), now());
INSERT INTO public.feed_provider_instances (id, provider_type, base_url, priority, enabled, last_success_at, last_failure_at, consecutive_failures, created_at, updated_at) VALUES ('7c8a803e-8b0e-4c3b-a2a3-a820b15ac74e', 'rsshub', 'https://rsshub.app', 200, false, NULL, NULL, 0, now(), now());
INSERT INTO public.feed_provider_instances (id, provider_type, base_url, priority, enabled, last_success_at, last_failure_at, consecutive_failures, created_at, updated_at) VALUES ('3e9d884f-3546-4432-84e3-e171cb6ef898', 'rsshub', 'https://rsshub.umzzz.com', 15, true, NULL, NULL, 0, now(), now());

INSERT INTO public.search_index_state (singleton, current_version, updated_at, target_version, cursor_created_at, cursor_document_id) VALUES (true, 0, now(), NULL, NULL, NULL);

INSERT INTO public.tts_voice_personas (id, user_id, display_name, description, provider, provider_voice_id, provider_model, design_prompt, style_prompt, pace, energy, warmth, formality, pronunciation_prefs, status, is_builtin, prompt_hash, created_at, updated_at) VALUES ('7a52a032-103e-4710-a0f2-23276b2cb754', NULL, 'Cherry (DashScope)', 'Default DashScope / Qwen voice', 'dashscope', 'Cherry', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{}', 'active', true, '', now(), now());
INSERT INTO public.tts_voice_personas (id, user_id, display_name, description, provider, provider_voice_id, provider_model, design_prompt, style_prompt, pace, energy, warmth, formality, pronunciation_prefs, status, is_builtin, prompt_hash, created_at, updated_at) VALUES ('dcd64195-3bb9-46de-b19a-c5eb1ca2d211', NULL, 'Chelsie (DashScope)', 'DashScope / Qwen female preset voice for TTS testing', 'dashscope', 'Chelsie', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{}', 'active', true, '', now(), now());
INSERT INTO public.tts_voice_personas (id, user_id, display_name, description, provider, provider_voice_id, provider_model, design_prompt, style_prompt, pace, energy, warmth, formality, pronunciation_prefs, status, is_builtin, prompt_hash, created_at, updated_at) VALUES ('d69a6295-4dc3-4a64-937d-bbd8b620b969', NULL, 'Vivian (DashScope)', 'DashScope / Qwen female preset voice for TTS testing', 'dashscope', 'Vivian', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{}', 'active', true, '', now(), now());
INSERT INTO public.tts_voice_personas (id, user_id, display_name, description, provider, provider_voice_id, provider_model, design_prompt, style_prompt, pace, energy, warmth, formality, pronunciation_prefs, status, is_builtin, prompt_hash, created_at, updated_at) VALUES ('c65d6276-0aa1-4bfa-ad31-bdf0f8bd2f22', NULL, 'Bunny (DashScope)', 'DashScope / Qwen female preset voice for TTS testing', 'dashscope', 'Bunny', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{}', 'active', true, '', now(), now());
INSERT INTO public.tts_voice_personas (id, user_id, display_name, description, provider, provider_voice_id, provider_model, design_prompt, style_prompt, pace, energy, warmth, formality, pronunciation_prefs, status, is_builtin, prompt_hash, created_at, updated_at) VALUES ('670b12d1-6eda-4087-a088-7e7b1c081df3', NULL, 'Jennifer (DashScope)', 'DashScope / Qwen female preset voice for TTS testing', 'dashscope', 'Jennifer', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{}', 'active', true, '', now(), now());
INSERT INTO public.tts_voice_personas (id, user_id, display_name, description, provider, provider_voice_id, provider_model, design_prompt, style_prompt, pace, energy, warmth, formality, pronunciation_prefs, status, is_builtin, prompt_hash, created_at, updated_at) VALUES ('09759978-8fd2-4dcb-8d58-261cd23b8709', NULL, 'Ono Anna (DashScope)', 'DashScope / Qwen female preset voice for TTS testing', 'dashscope', 'Ono Anna', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{}', 'active', true, '', now(), now());
INSERT INTO public.tts_voice_personas (id, user_id, display_name, description, provider, provider_voice_id, provider_model, design_prompt, style_prompt, pace, energy, warmth, formality, pronunciation_prefs, status, is_builtin, prompt_hash, created_at, updated_at) VALUES ('ef86a5ac-e883-458b-ac68-d2c4dc72f0bc', NULL, 'Sierra (Unreal Speech)', 'Default Unreal Speech voice', 'unreal_speech', 'Sierra', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{}', 'active', true, '', now(), now());
