mod ai_output_repo;
mod ai_preset_repo;
mod ai_run_repo;
mod apalis_job_repo;
mod api_token_repo;
mod authorization_code_repo;
mod background_job_recovery_repo;
mod billing_repo;
mod billing_usage_event_repo;
mod collection_repo;
mod content_vector_repo;
mod dead_letter_repo;
mod document_asset_repo;
mod document_lifecycle_repo;
mod document_note_repo;
pub(crate) mod document_repo;
mod document_reprocess_repo;
mod document_upload_repo;
mod email_alias_repo;
mod email_ingest_repo;
mod email_sender_repo;
mod email_unsubscribe_commit_repo;
mod email_unsubscribe_target_repo;
mod email_verification_repo;
mod embedding_backfill_repo;
mod entity_repo;
mod event_repo;
mod export_cursor_repo;
mod feed_delivery_repo;
mod feed_repo;
mod filter_sql;
mod highlight_repo;
mod home_repo;
mod import_job_repo;
mod integration_connection_repo;
mod integration_oauth_token_repo;
mod integrity_stats_repo;
mod library_query;
mod library_repo;
mod maintenance_task_repo;
mod mila_config_repo;
mod mila_session_repo;
mod notification_preferences_repo;
mod oauth_flow_repo;
mod oauth_identity_repo;
mod obsidian_export_repo;
mod obsidian_export_sync_repo;
mod obsidian_preview_repo;
pub mod outbox_handoff;
mod outbox_repo;
mod password_reset_repo;
mod playback_state_repo;
mod refresh_token_repo;
mod retention_cleanup_repo;
mod search_reindex_repo;
mod search_repo;
mod smart_list_repo;
mod tag_repo;
mod tts_audio_asset_repo;
mod tts_chunk_repo;
mod tts_element_timing_repo;
mod tts_session_repo;
mod tts_voice_persona_repo;
mod usage_counter_repo;
mod user_document_state_repo;
mod user_preferences_repo;
mod user_repo;
mod webhook_repo;
mod write_helpers;

pub use ai_output_repo::PgAiOutputRepository;
pub use ai_preset_repo::PgAiPromptPresetRepository;
pub use ai_run_repo::PgAiRunRepository;
pub use apalis_job_repo::PgApalisJobRepository;
pub use api_token_repo::PgApiTokenRepository;
pub use authorization_code_repo::PgAuthorizationCodeRepository;
pub use background_job_recovery_repo::PgBackgroundJobRecoveryRepository;
pub use billing_repo::PgBillingRepository;
pub use billing_usage_event_repo::PgBillingUsageEventRepository;
pub use collection_repo::PgCollectionRepository;
pub use content_vector_repo::PgContentVectorRepository;
pub use dead_letter_repo::PgDeadLetterRepository;
pub use document_asset_repo::PgDocumentAssetRepository;
pub use document_lifecycle_repo::PgDocumentLifecycle;
pub use document_note_repo::PgDocumentNoteRepository;
pub use document_repo::PgDocumentRepository;
pub use document_reprocess_repo::PgDocumentReprocessRepository;
pub use document_upload_repo::PgDocumentUploadRepository;
pub use email_alias_repo::PgEmailAliasRepository;
pub use email_ingest_repo::PgEmailIngestLogRepository;
pub use email_sender_repo::PgEmailSenderRepository;
pub use email_unsubscribe_commit_repo::PgEmailUnsubscribeCommit;
pub use email_unsubscribe_target_repo::PgEmailUnsubscribeTargetRepository;
pub use email_verification_repo::PgEmailVerificationRepository;
pub use embedding_backfill_repo::PgEmbeddingBackfillRepository;
pub use entity_repo::PgEntityRepository;
pub use event_repo::PgEventRepository;
pub use export_cursor_repo::PgExportCursorRepository;
pub use feed_delivery_repo::PgFeedDeliveryRepository;
pub use feed_repo::PgFeedRepository;
pub use highlight_repo::PgHighlightRepository;
pub use home_repo::PgHomeRepository;
pub use import_job_repo::PgImportJobRepository;
pub use integration_connection_repo::PgIntegrationConnectionRepository;
pub use integration_oauth_token_repo::PgIntegrationOAuthTokenRepository;
pub use integrity_stats_repo::PgIntegrityStatsRepository;
pub use library_repo::PgLibraryRepository;
pub use maintenance_task_repo::PgMaintenanceTaskRepository;
pub use mila_config_repo::PgMilaConfigRepository;
pub use mila_session_repo::PgMilaSessionRepository;
pub use notification_preferences_repo::PgNotificationPreferencesRepository;
pub use oauth_flow_repo::PgOAuthFlowRepository;
pub use oauth_identity_repo::PgOAuthIdentityRepository;
pub use obsidian_export_repo::PgObsidianExportRepository;
pub use obsidian_export_sync_repo::ObsidianSyncArtifactItemInsert;
pub use obsidian_preview_repo::PgObsidianPreviewRepository;
pub use outbox_handoff::PgOutboxHandoff;
pub use outbox_repo::PgJobOutboxRepository;
pub use password_reset_repo::PgPasswordResetRepository;
pub use playback_state_repo::PgPlaybackStateRepository;
pub use refresh_token_repo::PgRefreshTokenRepository;
pub use retention_cleanup_repo::PgRetentionCleanupRepository;
pub use search_reindex_repo::PgSearchReindexRepository;
pub use search_repo::PgSearchRepository;
pub use smart_list_repo::PgSmartListRepository;
pub use tag_repo::PgTagRepository;
pub use tts_audio_asset_repo::PgTtsAudioAssetRepository;
pub use tts_chunk_repo::PgTtsChunkRepository;
pub use tts_element_timing_repo::PgTtsElementTimingRepository;
pub use tts_session_repo::PgTtsSessionRepository;
pub use tts_voice_persona_repo::PgTtsVoicePersonaRepository;
pub use usage_counter_repo::PgUsageCounterRepository;
pub use user_document_state_repo::PgUserDocumentStateRepository;
pub use user_preferences_repo::PgUserPreferencesRepository;
pub use user_repo::PgUserRepository;
pub use webhook_repo::PgWebhookRepository;

use ind_application::AppError;
use ind_domain::DomainError;

fn map_sqlx_error(entity: &'static str, conflict_message: &str, err: sqlx::Error) -> AppError {
    if let sqlx::Error::Database(ref db_err) = err
        && db_err.code().as_deref() == Some("23505")
    {
        return AppError::Domain(DomainError::Conflict {
            entity,
            message: conflict_message.into(),
        });
    }
    AppError::Repository(Box::new(err))
}
