import type { AppIconName } from '../lib/icons';

/**
 * The signed-in user shown in every screen's sidebar.
 *
 * A placeholder, so the name is deliberately unremarkable: it should read as
 * "somebody" rather than as a particular person, and it appears in a greeting
 * ("Good morning, Morgan") where a distinctive name would pull focus.
 */
export const USER = { name: 'Morgan Reid', initials: 'MR' } as const;

export interface NavItem {
	key: AppIconName;
	label: string;
}

/**
 * The Library section of the sidebar.
 *
 * There is deliberately no Podcasts row: the icon exists but podcasts are not
 * a first-class library section yet, and the shipping app does not show one.
 */
export const LIBRARY_NAV: readonly NavItem[] = [
	{ key: 'articles', label: 'Articles' },
	{ key: 'books', label: 'Books' },
	{ key: 'emails', label: 'Emails' },
	{ key: 'pdfs', label: 'PDFs' },
	{ key: 'tweets', label: 'Tweets' },
	{ key: 'videos', label: 'Videos' },
	{ key: 'tags', label: 'Tags' },
	{ key: 'feed', label: 'Feed' },
];

/**
 * Mila's credits under generated text.
 *
 * The design source spells this both ways — five screens say "Summarized",
 * two say "Summarised". That is an inconsistency in the source, not a
 * convention, so the site picks the majority spelling and says it in one
 * place. Change it here and every panel follows.
 */
export const MILA_SUMMARY_CREDIT = 'Summarized by Mila';
export const MILA_ENTITY_CREDIT = 'Extracted by Mila';
export const MILA_ABOUT_CREDIT = 'Generated by Mila';
