#![allow(clippy::unwrap_used, clippy::expect_used, clippy::panic)]

mod api {
    mod access_policy_extractor_tests;
    mod account_email_capture_tests;
    mod account_locale_tests;
    mod ai_action_journey_tests;
    mod ai_asset_route_permission_tests;
    mod api_credential_boundary_tests;
    mod api_permission_enforcement_tests;
    mod api_token_issuance_tests;
    mod article_toc_journey_tests;
    mod asset_cookie_verification_tests;
    mod asset_serving_mode_tests;
    mod auth_recovery_journey_tests;
    mod auth_tests;
    mod common;
    mod disconnect_revocation_tests;
    mod document_annotation_journey_tests;
    mod document_search_tests;
    mod entity_resolution_journey_tests;
    mod extension_auth_journey_tests;
    mod feed_route_permission_tests;
    mod feed_subscription_journey_tests;
    mod highlight_text_quote_tests;
    mod integration_availability_tests;
    mod integration_journey_tests;
    mod integration_route_permission_tests;
    mod jwt_only_route_permission_tests;
    mod knowledge_settings_journey_tests;
    mod library_counts_journey_tests;
    mod library_ingest_failure_tests;
    mod library_route_permission_tests;
    mod media_journey_tests;
    mod mila_action_retry_journey_tests;
    mod mila_journey_tests;
    mod notion_control_journey_tests;
    mod notion_refresh_journey_tests;
    mod oauth_journey_tests;
    mod platform_journey_tests;
    mod product_journey_tests;
    mod realtime_journey_tests;
    mod resource_route_permission_support;
    mod save_pipeline_tests;
    mod search_api_journey_tests;
    mod upload_import_journey_tests;
    mod webhook_route_permission_tests;
    mod youtube_identity_journey_tests;
}
